[package]
name = "AutomaSploit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
pistol = "2.0.7"
rustscan = "2.3.0"
tokio = { version = "1.40.0", features = ["full"] }
nmap = "0.6.0"
